on:
  push:
    tags: ["*"]
    branches: ["main"]
  pull_request:

jobs:
  build:
    uses: visciang/gha-elixir-workflow/.github/workflows/elixir.yml@v1
    with:
      image: hexpm/elixir:1.18.0-erlang-27.2-debian-bookworm-20241223
    secrets: inherit
